# Using python for running the tests, using `cram` test framework.
language: python

# Python version to run tests with.
python:
  - "2.7"

before_script:

  # Show the git version being used to test.
  - "git --version"

  # Show the zsh version being used to test.
  - "zsh --version"

  # Test config for git.
  - "git config --global user.name test"
  - "git config --global user.email test@test.test"

install:
  # Install python requirements.
  - "pip install -r requirements.txt --use-mirrors"
  # Install zsh.
  - "sudo apt-get install zsh"
  # Add PPA if needed
  - 'if [ "$PPA" != "none" ]; then sudo apt-add-repository -y "$PPA"; sudo apt-get update -qq; fi'

# Run the tests.
script: "make tests"

env:
  # Default zsh
  - PPA = "none"
  # zsh 5 PPA
  - PPA = "ppa:brainpower/testing"
